import type { EditorThemeClasses } from 'lexical';

/**
 * Lexical EditorTheme configuration for trance-richtext-editor.
 * Maps Lexical node types to CSS class names used in editor.css.
 */
export const tranceLexicalTheme: EditorThemeClasses = {
  paragraph: 'trance-paragraph',
  heading: {
    h1: 'trance-h1',
    h2: 'trance-h2',
    h3: 'trance-h3',
    h4: 'trance-h4',
    h5: 'trance-h5',
    h6: 'trance-h6',
  },
  text: {
    bold: 'trance-bold',
    italic: 'trance-italic',
    underline: 'trance-underline',
    strikethrough: 'trance-strikethrough',
    underlineStrikethrough: 'trance-underline trance-strikethrough',
    code: 'trance-inline-code',
    highlight: 'trance-highlight',
    subscript: 'trance-subscript',
    superscript: 'trance-superscript',
  },
  list: {
    ul: 'trance-ul',
    ol: 'trance-ol',
    listitem: 'trance-li',
    listitemChecked: 'trance-li-checked',
    listitemUnchecked: 'trance-li-unchecked',
    nested: {
      listitem: 'trance-li-nested',
    },
  },
  link: 'trance-link',
  quote: 'trance-quote',
  code: 'trance-code-block',
  codeHighlight: {
    atrule: 'trance-token-atrule',
    attr: 'trance-token-attr',
    boolean: 'trance-token-boolean',
    builtin: 'trance-token-builtin',
    cdata: 'trance-token-cdata',
    char: 'trance-token-char',
    class: 'trance-token-class',
    'class-name': 'trance-token-class-name',
    comment: 'trance-token-comment',
    constant: 'trance-token-constant',
    deleted: 'trance-token-deleted',
    doctype: 'trance-token-doctype',
    entity: 'trance-token-entity',
    function: 'trance-token-function',
    important: 'trance-token-important',
    inserted: 'trance-token-inserted',
    keyword: 'trance-token-keyword',
    namespace: 'trance-token-namespace',
    number: 'trance-token-number',
    operator: 'trance-token-operator',
    prolog: 'trance-token-prolog',
    property: 'trance-token-property',
    punctuation: 'trance-token-punctuation',
    regex: 'trance-token-regex',
    selector: 'trance-token-selector',
    string: 'trance-token-string',
    symbol: 'trance-token-symbol',
    tag: 'trance-token-tag',
    url: 'trance-token-url',
    variable: 'trance-token-variable',
  },
  table: 'trance-table',
  tableCell: 'trance-table-cell',
  tableCellHeader: 'trance-table-cell-header',
  tableRow: 'trance-table-row',
  tableRowStriped: 'trance-table-row-striped',
  horizontalRule: 'trance-hr',
  image: 'trance-image-wrapper',
  indent: 'trance-indent',
  ltr: 'trance-text-left',
  rtl: 'trance-text-right',
};
